#!/bin/bash

tree previous_semesters -fi --noreport > files 
mkdir -p material
for x in $(grep '.pdf' files); do 
    echo "Found pdf: $x" 
    name=$(basename $(realpath $x))
    echo "Name: $name"
   # mv "$x" "material/$x"; 
done

