apiVersion: apps/v1
kind: Deployment
metadata:
  name: jogodavida-deployment
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jogodavida
  template:
    metadata:
      labels:
        app: jogodavida
    spec:
      containers:
      - name: jogodavida-container-mpispark
        image: registry.digitalocean.com/pspd/mpi:0.0.22