/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "somalista.h"

bool_t
xdr_lista (XDR *xdrs, lista *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->num))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->prox, sizeof (lista), (xdrproc_t) xdr_lista))
		 return FALSE;
	return TRUE;
}
