/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "somalista.h"

int *somal_1_svc(lista *argp, struct svc_req *rqstp)
{
	static int result;
	lista local = *argp;
	result = 0;
	printf("Starting calculation with result=%d and first value %d", result, local->num);
	while (local->prox)
	{
		result += local->prox->num;
		local = local->prox;
	}

	return &result;
}
