/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "somalista.h"

int *
somal_1_svc(lista *argp, struct svc_req *rqstp)
{
	static int  result;
	lista *ap_lista;

	ap_lista = argp;
	/*
	 * insert server code here
	 */
	result = 0;
	while (ap_lista) {
		printf("%d ", ap_lista->num);
		result +=ap_lista->num;
		ap_lista=ap_lista->prox;
	} /* fim-while */
	printf("A soma eh ... %d\n", result);

	return &result;
}
