/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "somalista.h"


void imprimelista(CLIENT *clnt, lista *ap) {
	int  *res;

	res = somal_1(ap, clnt);
	if (res == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	clnt_destroy (clnt);
} /* fim-imprimelista */


int main (int argc, char *argv[]) {
	CLIENT  *clnt;
	lista	*ap, *inicio_lista, *apaux;
	int	n_termos, i;

	if (argc < 3) {
		printf ("usage: %s server_host num1 num2 ...\n", argv[0]);
		exit (1);
	}
	n_termos = argc - 2;
	inicio_lista = (lista *) malloc(sizeof(lista));
	ap = inicio_lista;
	for (i=0;i<n_termos; i++) {
		ap->num=atoi(argv[i+2]);
		ap->prox = (lista *) malloc(sizeof(lista));
		apaux = ap;
		ap = ap->prox;
	} /* fim-for */
	free(apaux->prox);
	apaux->prox=NULL;

	clnt = clnt_create (argv[1], SOMALISTA_PROG, SOMALISTA_VERSION, "udp");
	imprimelista(clnt, inicio_lista);

	exit (0);
} /* fim-main */
